name: Production C Build

on:
  push:
    branches: [ "main" ]

jobs:
  release-build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Compile with Commit ID
      run: |
        SHORT_SHA=$(git rev-parse --short HEAD)
        gcc -DVERSION="\"$SHORT_SHA\"" -o app_${SHORT_SHA} main.c

    - name: Upload Executable Artifact
      uses: actions/upload-artifact@v4
      with:
        name: compiled-application
        path: app_*
